### PR TITLE
Include reference to missing article in README.md

### PR DESCRIPTION
**Pull request by maeichris**
The JXMapViewer Tutorial by Joshua Marinacci, linked through archive.org.

### CODE REVIEW

**Comment by msteiger** [comment]
Thanks for the hint ... it looks like it contains only the main overview page, but not the actual article about JXMapViewer. Am I missing something?

**Comment by maeichris** [comment]
No, that was my fault.  I must have had too many tabs open at the time and copied the URL from the wrong one, sorry.

The correct URL is:

https://web.archive.org/web/20100309081606/http://today.java.net/pub/a/today/2007/10/30/building-maps-into-swing-app-with-jxmapviewer.html

What's the best way to fix my botched pull request?

**Comment by msteiger** [comment]
You can just create a new commit on your branch. It will be added automatically to this PR.

**Comment by maeichris** [comment]
The correction has been made, and it appears in the pull request as you mentioned.  Thanks for your patience.

**Comment by msteiger** [comment]
Thanks, looks good to me!

**Pull request merged**
