### PR TITLE
Avoid potential race condition when getting local cached file. 

### PR DESCRIPTION
**Pull request by kkieffer**
Address Issue https://github.com/msteiger/jxmapviewer2/issues/96.

### CODE REVIEW

**Comment by msteiger** [comment]
Hmm ... interesting. I guess it could still happen a moment later when someone force-deletes the file. Maybe the try-catch should be around the loading part of the image. Will have a look over the weekend, I hope.

**Comment by kkieffer** [comment]
Once the Input Stream is opened, a process trying to delete that file should get denied (file in use) should it not?

**Comment by kkieffer** [comment]
Sorry to add on to the PR but I needed a property listener on tiles failing to load...

**Review by msteiger — APPROVED** [review]
You're right, thanks ...

**Comment by kkieffer** [comment]
Would be great to get a new release for maven too, at some point...thanks!

**Pull request merged**
