### PR TITLE
Offline maps example

### LINKED ISSUE #72: Example for offline maps
May you give me an example hot to use offline map tiles from OSM with JXMapViewer2?

### PR DESCRIPTION
**Pull request by msteiger**
An alternative implementation of #75 to illustrate offline maps.

Fixes #72.

### CODE REVIEW

**Comment by canacar7** [comment]
How can I create the openstreetmap.zip?

**Comment by msteiger** [comment]
I think that the easiest way is to just zip the cache folder. Do you know how to do that?

**Comment by canacar7** [comment]
No, I don't know this way. While searching on the internet, I had the openstreetmap tiles files in the format (0,1,2,3..) produced using the Qgis application, but I was not successful.

**Comment by msteiger** [comment]
Here's a snippet that sets up a local cache folder: https://github.com/msteiger/jxmapviewer2/blob/master/examples/src/sample4_fancy/Sample4.java#L41-L42

You can just create a zip archive from that folder. Does that help?

**Pull request merged**
