### PR TITLE
Issue#119 - Adding possibility to custom limit the amount of stored tiles in TileMap

### PR DESCRIPTION
**Pull request by MaxKoenig94**
adding additional value to TileFactoryInfo to limit the size and prohibit an out of memory exception caused by the map

### CODE REVIEW

**Comment by msteiger** [comment]
Thanks for this PR and sorry for the delay in reviewing it. It's top of my TODO list now, but still might need a few days.

**Comment by msteiger** [comment]
Sorry for the super-long delay in reviewing this. You're right about the problem, the `tileMap` instance is never cleaned up - the whole code is quite a mess :-D

I wondered if it was possible to use `tileMap` directly to manage some kind of LRU map and came up with this:  https://github.com/msteiger/jxmapviewer2/pull/121

It's based on your first commit - what do you think?

**Comment by MaxKoenig94** [comment]
looks suitable to me.

**Comment by msteiger** [comment]
Thanks a lot for your help!

**Comment by msteiger** [comment]
Thanks! Closing this PR then ...

**Pull request closed without merging**
