### PR TITLE
fixed ArrayIndexOutOfBoundsException in zoomToBestFit

### PR DESCRIPTION
**Pull request by dansch1**

### CODE REVIEW

**Comment by msteiger** [comment]
Looks good to me .. do you have an example where the AIOOBE happened before this fix?

**Comment by dansch1** [comment]
GeoPosition(0, 0), GeoPosition(1, 0) - it happens when the positions are really close to each other

**Comment by msteiger** [comment]
Sorry for the delay, will have a look asap.

**Comment by msteiger** [comment]
Looks great, thanks!

**Pull request merged**
