### PR TITLE
support enabling / disabling input sources

### PR DESCRIPTION
**Pull request by bradh**
This is a first cut on a filtering (proxy?) wrapper for the input sources, based on #110 feedback.

### CODE REVIEW

**Comment by msteiger** [comment]
Thanks, will review as soon as I can.

**Comment by bradh** [comment]
@msteiger Did you have any further thoughts on this? Should I plan an update, mark it for review, or close it?

**Comment by msteiger** [comment]
Hey, sorry, still haven't managed to review. Will do it this week, I hope.

**Comment by bradh** [comment]
OK. No real rush.

**Comment by msteiger** [comment]
Sorry for the huge delay! It looks good imho and probably does the job. In my opinion it could be part of the "examples" project, but I can move it later, so no worries.

Maybe it could be simplified even more: instead of explicitly checking the "enabled" flag, you could replace the entire implementation when switching it on/off. Your key/mouse listener (the one you attach to the map viewer) delegates to your real listener of a dummy one that does nothing depending on the current state. Does that make sense?

Here's a better description maybe: http://best-practice-software-engineering.ifs.tuwien.ac.at/patterns/delegation.html

**Comment by bradh** [comment]
OK. Have marked it as ready for review.

The reason for the boolean is that makes it easy to bind to a checkbox or similar UI element. Otherwise there needs to be a separate listener that switches the implementations in/out.

**Comment by msteiger** [comment]
My apologies for this super long delay .. please have a look on my alternative implementation and let me know what you think.

**Comment by bradh** [comment]
Closing in favour of #113

**Pull request closed without merging**
